Проверка статуса ssh канала перед записью.
bazhenov/groovy-shell-server pull request #30
Opened 2021-01-20 06:48 UTC by demidko

Существует редкий сценарий, как, например при ручном вызове 'groovyShell.destroy()' из сессии самого GroovyShell, при котором результат команды не может быть отображен пользователю, поскольку ssh канал уже закрыт, что вызывает рекурсивный поток ошибок при попытке вывести пользователю уже исключение, что засоряет логи самого приложения эксплуатирующего GroovyShellServiceBean.
Решение:
Добавил явную проверку в записыающий поток для этого случая, чтобы погасить рекурсивный поток исключений и завершить работу.

2021-01-21 03:49 UTC, bazhenov requested changes

2021-01-21 03:49 UTC, bazhenov commented on groovy-shell-server/src/main/java/me/bazhenov/groovysh/TtyFilterOutputStream.java
> +	private final AtomicBoolean isChannelAlive;
Так уж получилось что этот проект у нас OSS. Так что комментарии тут пишем на английском и самодостаточные, потому что у людей извне нет возможности ознакомится с нашим issue tracker'ом.

2021-01-21 04:44 UTC, demidko commented on groovy-shell-server/src/main/java/me/bazhenov/groovysh/TtyFilterOutputStream.java
> +	private final AtomicBoolean isChannelAlive;
Готово

2021-01-21 04:44 UTC, demidko commented on groovy-shell-server/src/main/java/me/bazhenov/groovysh/TtyFilterOutputStream.java
> +	private final AtomicBoolean isChannelAlive;
> Так уж получилось что этот проект у нас OSS. Так что комментарии тут пишем на английском и самодостаточные, потому что у людей извне нет возможности ознакомится с нашим issue tracker'ом.

готово

2021-01-21 08:49 UTC, merged

2021-01-25 00:30 UTC, bazhenov commented
2.1.1 released